# 左手側（トラックボールがある側）専用の設定
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_PMW3610=y

# 向き設定（上下左右が逆ならここを y に変更）
CONFIG_PMW3610_ORIENTATION_180=n

# 感度・動作設定
CONFIG_PMW3610_CPI=1200
CONFIG_PMW3610_SNIPE_CPI=400
CONFIG_PMW3610_SMART_ALGORITHM=y
