manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: keyball-driver-final
      url: https://github.com/Yisheng-shiao/zmk-pmw3610-driver
      revision: main
  self:
    path: config
